
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src


COPY ClinicalMS/ClinicalMS.csproj ClinicalMS/
RUN dotnet restore ClinicalMS/ClinicalMS.csproj


COPY . .


WORKDIR /src/ClinicalMS
RUN dotnet publish ClinicalMS.csproj -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false


FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app


ENV ASPNETCORE_URLS=http://+:8080

COPY --from=build /app/publish ./

EXPOSE 8080
ENTRYPOINT ["dotnet", "ClinicalMS.dll"]



